<?php

namespace MI\BilletterieBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTotalTickets($selectedDate)
    {
        $query = $this->createQueryBuilder('t')
            ->where('t.dateEntree = :dateEntree')
            ->setParameter('dateEntree', $selectedDate)
            ->select('SUM(t.NbBillet)')
            ->getQuery()
            ;
        return $query->getSingleScalarResult();
    }
}
