mi_billetterie_homepage:
    path:     /Billetterie
    defaults: { _controller: MIBilletterieBundle:Home:index }

mi_billetterie_choixbillet:
    path:     /Billetterie/Choix_Billet
    defaults: { _controller: MIBilletterieBundle:Home:choose }

mi_billetterie_champsbillet:
    path:     /Billetterie/Champs_Billet
    defaults: { _controller: MIBilletterieBundle:Home:champs }

